import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.milex.app',
  appName: 'MileX',
  webDir: 'out', // Points to Next.js static export (generated by: npm run build:android)

  // ── DEV ONLY: Uncomment below to use live reload from your Mac's dev server ──
  // This lets you see code changes instantly on your phone/emulator without rebuilding.
  // Make sure your phone and Mac are on the same WiFi network.
  // Replace the IP with your Mac's local IP (run: ifconfig | grep 192)
  // server: {
  //   url: 'http://192.168.x.x:3000/app',
  //   cleartext: true,
  // },
};

export default config;
